import tap from 'tap'
import fs from 'fs-extra'
import { runCommand } from '../src/commands/json2ts.js'
import { resolveFromPackageRoot } from '../src/utils/paths.js'
import { doNotEditText } from '../src/utils/do-not-edit-text.js'

const TEST_DIRECTORY = resolveFromPackageRoot('test', 'temp')

const inputPath = './test/fixtures/schemas'
const outputPath = './test/temp/types'

tap.test('json2ts', t => {
  t.test('runCommand function', async t => {
    fs.ensureDirSync(TEST_DIRECTORY)

    const customOptions = {
      bannerComment: doNotEditText
    }

    await runCommand(inputPath, outputPath, customOptions)

    const PetFile = resolveFromPackageRoot(outputPath, 'Pet.d.ts')

    t.ok(fs.existsSync(PetFile), 'Pet.d.ts file should exist')
    const generatedPetFile = fs.readFileSync(PetFile, 'utf-8')

    t.same(
      generatedPetFile,
      `import { Category } from './Category'
import { Tag } from './Tag'

/* tslint:disable */
/**
 * This file was automatically generated by oas-codegen CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run oas-codegen CLI to regenerate this file.
 */

export interface Pet {
  id?: number;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  /**
   * pet status in the store
   */
  status?: "available" | "pending" | "sold";
  [k: string]: unknown;
}
`,
      'Pet.d.ts is created correctly'
    )
  })

  const CustomerFile = resolveFromPackageRoot(outputPath, 'Customer.d.ts')
  t.ok(fs.existsSync(CustomerFile), 'Customer.d.ts file should exist')
  const generatedCustomerFile = fs.readFileSync(CustomerFile, 'utf-8')

  t.same(
    generatedCustomerFile,
    `import { Address } from './Address'

/* tslint:disable */
/**
 * This file was automatically generated by oas-codegen CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run oas-codegen CLI to regenerate this file.
 */

export interface Customer {
  id?: number;
  username?: string;
  address?: Address[];
  [k: string]: unknown;
}
`,
    'Customer.d.ts is created correctly'
  )

  t.end()
})
