import fs from 'fs-extra'
import tap from 'tap'
import { runCommand } from '../src/commands/json2ts.js'
import { doNotEditText } from '../src/utils/do-not-edit-text.js'
import { resolveFromPackageRoot } from '../src/utils/paths.js'

const TEST_DIRECTORY = resolveFromPackageRoot('test', 'temp')

const inputPath = './test/fixtures/schemas'
const outputPath = './test/temp/types-from-json'

tap.test('json2ts runCommand', async t => {
  fs.ensureDirSync(TEST_DIRECTORY)

  const customOptions = {
    bannerComment: doNotEditText
  }

  await runCommand(inputPath, outputPath, customOptions)

  const generatedFiles = fs.readdirSync(outputPath)
  t.match(
    generatedFiles,
    [
      'Address.d.ts',
      'ApiResponse.d.ts',
      'Category.d.ts',
      'Customer.d.ts',
      'DateExample.d.ts',
      'Order.d.ts',
      'Pet.d.ts',
      'Tag.d.ts',
      'User.d.ts'
    ],
    'generates the expected TS files'
  )

  const PetFile = resolveFromPackageRoot(outputPath, 'Pet.d.ts')
  const generatedPetFile = fs.readFileSync(PetFile, 'utf-8')

  t.same(
    generatedPetFile,
    `import { Category } from "./Category";
import { Tag } from "./Tag";

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface Pet {
  id?: number;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  /**
   * pet status in the store
   */
  status?: "available" | "pending" | "sold";
  [k: string]: unknown;
}
`,
    'Pet.d.ts is created correctly'
  )

  const CustomerFile = resolveFromPackageRoot(outputPath, 'Customer.d.ts')
  const generatedCustomerFile = fs.readFileSync(CustomerFile, 'utf-8')

  t.same(
    generatedCustomerFile,
    `import { Address } from "./Address";

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface Customer {
  id?: number;
  username?: string;
  address?: Address[];
  [k: string]: unknown;
}
`,
    'Customer.d.ts is created correctly'
  )
})
