import fs from 'fs-extra'
import { describe, test, TestContext } from 'node:test'
import { runCommand } from '../src/commands/oas2ts.js'
import { resolveFromPackageRoot } from '../src/utils/paths.js'

const TEST_DIRECTORY = resolveFromPackageRoot('test', 'temp')

const inputPath = './test/fixtures/openapi.yml'
const outputPath = './test/temp/types-from-oas'

describe('oas2ts', () => {
  test('runCommand function', async (t: TestContext) => {
    fs.ensureDirSync(TEST_DIRECTORY)

    await runCommand(inputPath, outputPath)

    const generatedFiles = fs.readdirSync(outputPath)
    t.assert.deepStrictEqual(
      generatedFiles,
      [
        'Address.d.ts',
        'ApiResponse.d.ts',
        'Category.d.ts',
        'Customer.d.ts',
        'DateExample.d.ts',
        'FooBARBaz.d.ts',
        'Order.d.ts',
        'Pet.d.ts',
        'Tag.d.ts',
        'User.d.ts'
      ],
      'generates the expected TS files'
    )

    const petFile = resolveFromPackageRoot(outputPath, 'Pet.d.ts')
    const generatedPetFile = fs.readFileSync(petFile, 'utf-8')

    t.assert.deepStrictEqual(
      generatedPetFile,
      `import { Category } from "./Category";
import { Tag } from "./Tag";

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface Pet {
  id?: number;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  /**
   * pet status in the store
   */
  status?: "available" | "pending" | "sold";
  /**
   * example nullable value
   */
  nullableValue?: string | null;
  [k: string]: unknown;
}
`,
      'Pet.d.ts is created correctly'
    )

    const customerFile = resolveFromPackageRoot(outputPath, 'Customer.d.ts')
    const generatedCustomerFile = fs.readFileSync(customerFile, 'utf-8')

    t.assert.deepStrictEqual(
      generatedCustomerFile,
      `import { Address } from "./Address";

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface Customer {
  id?: number;
  username?: string;
  address?: Address[];
  [k: string]: unknown;
}
`,
      'Customer.d.ts is created correctly'
    )
  })
})
