import { FooBARBaz } from './FooBARBaz';

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface APIResponse {
  code?: number;
  type?: string;
  message?: string;
  FooBARBaz?: FooBARBaz;
  [k: string]: unknown;
}
