import { Pet } from '../components.schemas/Pet'
import { Category } from '../components.schemas/Category'
import { Tag } from '../components.schemas/Tag'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface Pet {
  /**
   * Update an existing pet by Id
   */
  put: {
    /**
     * Update an existent pet in the store
     */
    requestBody: {
      content?: {
        'application/json'?: Pet1;
        'application/xml'?: Pet2;
        'application/x-www-form-urlencoded'?: Pet3;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        'application/json'?: Pet4;
        'application/xml'?: Pet5;
        [k: string]: unknown;
      };
      /**
       * Invalid ID supplied
       */
      '400'?: {
        [k: string]: unknown;
      };
      /**
       * Pet not found
       */
      '404'?: {
        [k: string]: unknown;
      };
      /**
       * Validation exception
       */
      '405'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Add a new pet to the store
   */
  post: {
    /**
     * Create a new pet in the store
     */
    requestBody: {
      content?: {
        'application/json'?: Pet6;
        'application/xml'?: Pet7;
        'application/x-www-form-urlencoded'?: Pet8;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        'application/json'?: Pet9;
        'application/xml'?: Pet10;
        [k: string]: unknown;
      };
      /**
       * Invalid input
       */
      '405'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
