import { Pet } from '../components.schemas/Pet'
import { Category } from '../components.schemas/Category'
import { Tag } from '../components.schemas/Tag'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface PetFindByStatus {
  /**
   * Multiple status values can be provided with comma separated strings
   */
  get: {
    parameters: {
      /**
       * Status values that need to be considered for filter
       */
      status?: 'available' | 'pending' | 'sold';
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        /**
         * successful operation
         */
        'application/json'?: Pet[];
        /**
         * successful operation
         */
        'application/xml'?: Pet[];
        [k: string]: unknown;
      };
      /**
       * Invalid status value
       */
      '400'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
