import { Pet } from '../components.schemas/Pet'
import { Category } from '../components.schemas/Category'
import { Tag } from '../components.schemas/Tag'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface PetFindByTags {
  /**
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   */
  get: {
    parameters: {
      /**
       * Tags to filter by
       */
      tags?: string[];
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        /**
         * successful operation
         */
        'application/json'?: Pet[];
        /**
         * successful operation
         */
        'application/xml'?: Pet[];
        [k: string]: unknown;
      };
      /**
       * Invalid tag value
       */
      '400'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
