import { Pet } from '../components.schemas/Pet'
import { Category } from '../components.schemas/Category'
import { Tag } from '../components.schemas/Tag'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface PetPetId {
  /**
   * Returns a single pet
   */
  get: {
    parameters: {
      /**
       * ID of pet to return
       */
      petId: number;
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        'application/json'?: Pet;
        'application/xml'?: Pet1;
        [k: string]: unknown;
      };
      /**
       * Invalid ID supplied
       */
      '400'?: {
        [k: string]: unknown;
      };
      /**
       * Pet not found
       */
      '404'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  post: {
    parameters: {
      /**
       * ID of pet that needs to be updated
       */
      petId: number;
      /**
       * Name of pet that needs to be updated
       */
      name?: string;
      /**
       * Status of pet that needs to be updated
       */
      status?: string;
      [k: string]: unknown;
    };
    responses: {
      /**
       * Invalid input
       */
      '405'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * delete a pet
   */
  delete: {
    parameters: {
      api_key?: string;
      /**
       * Pet id to delete
       */
      petId: number;
      [k: string]: unknown;
    };
    responses: {
      /**
       * Invalid pet value
       */
      '400'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
