import { ApiResponse } from '../components.schemas/ApiResponse'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface PetPetIdUploadImage {
  post: {
    requestBody?: {
      content?: {
        'application/octet-stream'?: unknown;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    parameters: {
      /**
       * ID of pet to update
       */
      petId: number;
      /**
       * Additional Metadata
       */
      additionalMetadata?: string;
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        'application/json'?: ApiResponse;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
