import { Order } from '../components.schemas/Order'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface StoreOrder {
  /**
   * Place a new order in the store
   */
  post: {
    requestBody?: {
      content?: {
        'application/json'?: Order;
        'application/xml'?: Order;
        'application/x-www-form-urlencoded'?: Order;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        'application/json'?: Order1;
        [k: string]: unknown;
      };
      /**
       * Invalid input
       */
      '405'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
