/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface StoreInventory {
  /**
   * Returns a map of status codes to quantities
   */
  get: {
    responses: {
      '200'?: {
        /**
         * successful operation
         */
        'application/json'?: {
          [k: string]: number;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
