import { Order } from '../components.schemas/Order'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface StoreOrderOrderId {
  /**
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   */
  get: {
    parameters: {
      /**
       * ID of order that needs to be fetched
       */
      orderId: number;
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        'application/json'?: Order;
        'application/xml'?: Order1;
        [k: string]: unknown;
      };
      /**
       * Invalid ID supplied
       */
      '400'?: {
        [k: string]: unknown;
      };
      /**
       * Order not found
       */
      '404'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
   */
  delete: {
    parameters: {
      /**
       * ID of the order that needs to be deleted
       */
      orderId: number;
      [k: string]: unknown;
    };
    responses: {
      /**
       * Invalid ID supplied
       */
      '400'?: {
        [k: string]: unknown;
      };
      /**
       * Order not found
       */
      '404'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
