import { User } from '../components.schemas/User'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface UserCreateWithList {
  /**
   * Creates list of users with given input array
   */
  post: {
    requestBody?: {
      content?: {
        'application/json'?: unknown;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        'application/json'?: User;
        'application/xml'?: User1;
        [k: string]: unknown;
      };
      /**
       * successful operation
       */
      default?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
