import { User } from '../components.schemas/User'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface User {
  /**
   * This can only be done by the logged in user.
   */
  post: {
    /**
     * Created user object
     */
    requestBody?: {
      content?: {
        'application/json'?: User1;
        'application/xml'?: User2;
        'application/x-www-form-urlencoded'?: User3;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    responses: {
      default?: {
        'application/json'?: User4;
        'application/xml'?: User5;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
