import { User } from '../components.schemas/User'

/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface UserUsername {
  get: {
    parameters: {
      /**
       * The name that needs to be fetched. Use user1 for testing.
       */
      username: string;
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        'application/json'?: User;
        'application/xml'?: User1;
        [k: string]: unknown;
      };
      /**
       * Invalid username supplied
       */
      '400'?: {
        [k: string]: unknown;
      };
      /**
       * User not found
       */
      '404'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * This can only be done by the logged in user.
   */
  put: {
    /**
     * Update an existent user in the store
     */
    requestBody?: {
      content?: {
        'application/json'?: User2;
        'application/xml'?: User3;
        'application/x-www-form-urlencoded'?: User4;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    parameters: {
      /**
       * name that need to be deleted
       */
      username: string;
      [k: string]: unknown;
    };
    responses: {
      /**
       * successful operation
       */
      default?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * This can only be done by the logged in user.
   */
  delete: {
    parameters: {
      /**
       * The name that needs to be deleted
       */
      username: string;
      [k: string]: unknown;
    };
    responses: {
      /**
       * Invalid username supplied
       */
      '400'?: {
        [k: string]: unknown;
      };
      /**
       * User not found
       */
      '404'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
