/* eslint-disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI/methods.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI/methods to regenerate this file.
 */

export interface UserLogin {
  get: {
    parameters: {
      /**
       * The user name for login
       */
      username?: string;
      /**
       * The password for login in clear text
       */
      password?: string;
      [k: string]: unknown;
    };
    responses: {
      '200'?: {
        /**
         * successful operation
         */
        'application/xml'?: string;
        /**
         * successful operation
         */
        'application/json'?: string;
        [k: string]: unknown;
      };
      /**
       * Invalid username/password supplied
       */
      '400'?: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
