/* tslint:disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI to regenerate this file.
 */

export interface Address {
  street?: string;
  city?: string;
  state?: string;
  zip?: string;
  [k: string]: unknown;
}
