/* tslint:disable */
/**
 * This file was automatically generated by oas-codegen CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run oas-codegen CLI to regenerate this file.
 */

export interface ApiResponse {
  code?: number;
  type?: string;
  message?: string;
  [k: string]: unknown;
}
