/* tslint:disable */
/**
 * This file was automatically generated by openapi-codegen CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-codegen CLI to regenerate this file.
 */

export interface Category {
  id?: number;
  name?: string;
  [k: string]: unknown;
}
