import { Address } from './Address'

/* tslint:disable */
/**
 * This file was automatically generated by openapi-transformer-toolkit CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-transformer-toolkit CLI to regenerate this file.
 */

export interface Customer {
  id?: number;
  username?: string;
  address?: Address[];
  [k: string]: unknown;
}
