/* tslint:disable */
/**
 * This file was automatically generated by oas-codegen CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run oas-codegen CLI to regenerate this file.
 */
 
 export interface Id {
	type: string;
	format: string;
	minimum: number;
	maximum: number;
}

export interface Name {
	type: string;
}

export interface Property {
	id: Id;
	name: Name;
}

export interface Tag {
	type: string;
	properties: Property;
	title: string;
	$id: string;
}