/* tslint:disable */
/**
 * This file was automatically generated by oas-codegen CLI.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run oas-codegen CLI to regenerate this file.
 */

export interface Tag {
  id?: number;
  name?: string;
  [k: string]: unknown;
}
